# Generated by Django 5.1.6 on 2025-02-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="route_code",
            field=models.CharField(
                editable=False, max_length=7, null=True, unique=True
            ),
        ),
    ]
