# Generated by Django 5.1.6 on 2025-02-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_route_route_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="route_code",
            field=models.CharField(editable=False, max_length=7, unique=True),
        ),
    ]
