# Generated by Django 5.1.6 on 2025-02-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_route_route_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="crewgroup",
            name="crew_code",
            field=models.CharField(max_length=5, null=True, unique=True),
        ),
    ]
