# Generated by Django 5.1.6 on 2025-02-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_crewgroup_crew_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crewgroup",
            name="crew_code",
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
