# Generated by Django 5.1.6 on 2025-02-28 23:25

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_crewgroup_crew_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="crewmember",
            name="photo",
            field=models.ImageField(
                null=True, upload_to=core.models.crew_member_image_path
            ),
        ),
    ]
